This Program demonstrates how panda library could be used to read different file formats and process the data

In [22]:
import pandas as pd

try:
    df = pd.read_csv("../dataset/student_performance.csv")
except Exception as e:
    print(f"Exception: {e}")

df

,student_id,gender,age,study_hours_per_week,attendance_rate,parent_education,internet_access,extracurricular,previous_score,final_score,passed
0,STU0001,Male,15,25,63.8,Bachelor,Yes,Yes,41,67,Yes
1,STU0002,Female,15,2,54.7,Bachelor,Yes,Yes,83,28,No
2,STU0003,Female,19,10,90.5,High School,Yes,No,73,49,No
3,STU0004,Male,16,26,66.8,High School,No,Yes,75,70,Yes
4,STU0005,Female,15,25,73.0,High School,No,Yes,67,77,Yes
...,...,...,...,...,...,...,...,...,...,...,...
495,STU0496,Female,19,6,78.3,Master,No,No,51,27,No
496,STU0497,Female,16,27,61.1,PhD,No,No,47,74,Yes
497,STU0498,Female,18,16,72.3,Master,No,Yes,52,61,Yes
498,STU0499,Male,17,29,91.3,NaN,Yes,No,39,86,Yes
499,STU0500,Male,15,29,75.4,High School,No,Yes,34,74,Yes

Display first three rows only

In [23]:

df.head(3)

,student_id,gender,age,study_hours_per_week,attendance_rate,parent_education,internet_access,extracurricular,previous_score,final_score,passed
0,STU0001,Male,15,25,63.8,Bachelor,Yes,Yes,41,67,Yes
1,STU0002,Female,15,2,54.7,Bachelor,Yes,Yes,83,28,No
2,STU0003,Female,19,10,90.5,High School,Yes,No,73,49,No

In [24]:
# dispaly only price column from data frame
df["student_id"]

0      STU0001
1      STU0002
2      STU0003
3      STU0004
4      STU0005
        ...
495    STU0496
496    STU0497
497    STU0498
498    STU0499
499    STU0500
Name: student_id, Length: 500, dtype: str

In [25]:
df[["student_id", "gender", "age"]]

    student_id  gender  age
0      STU0001    Male   15
1      STU0002  Female   15
2      STU0003  Female   19
3      STU0004    Male   16
4      STU0005  Female   15
..         ...     ...  ...
495    STU0496  Female   19
496    STU0497  Female   16
497    STU0498  Female   18
498    STU0499    Male   17
499    STU0500    Male   15

[500 rows x 3 columns]

Below is the example how data could be filtered base on specific condition
df[df["price"] > 350]

In [26]:
df[df["age"] < 18]

,student_id,gender,age,study_hours_per_week,attendance_rate,parent_education,internet_access,extracurricular,previous_score,final_score,passed
0,STU0001,Male,15,25,63.8,Bachelor,Yes,Yes,41,67,Yes
1,STU0002,Female,15,2,54.7,Bachelor,Yes,Yes,83,28,No
3,STU0004,Male,16,26,66.8,High School,No,Yes,75,70,Yes
4,STU0005,Female,15,25,73.0,High School,No,Yes,67,77,Yes
7,STU0008,Female,15,21,81.7,NaN,Yes,Yes,89,70,Yes
...,...,...,...,...,...,...,...,...,...,...,...
493,STU0494,Male,17,5,59.9,NaN,No,No,75,29,No
494,STU0495,Male,15,11,81.0,Bachelor,No,No,87,53,Yes
496,STU0497,Female,16,27,61.1,PhD,No,No,47,74,Yes
498,STU0499,Male,17,29,91.3,NaN,Yes,No,39,86,Yes
499,STU0500,Male,15,29,75.4,High School,No,Yes,34,74,Yes

Below is the example how data could be filtered base on specific condition
df[df["price"] > 350]["sqft"]

In [27]:
df[df["age"] > 18]["student_id"]

2      STU0003
5      STU0006
8      STU0009
12     STU0013
13     STU0014
        ...
468    STU0469
474    STU0475
486    STU0487
490    STU0491
495    STU0496
Name: student_id, Length: 102, dtype: str

In pandas queries can be used to filter data as per requirement

In [28]:
df.query("age > 18").head()

,student_id,gender,age,study_hours_per_week,attendance_rate,parent_education,internet_access,extracurricular,previous_score,final_score,passed
2,STU0003,Female,19,10,90.5,High School,Yes,No,73,49,No
5,STU0006,Female,19,8,85.2,High School,Yes,No,40,37,No
8,STU0009,Female,19,9,84.2,High School,Yes,Yes,70,49,No
12,STU0013,Female,19,4,69.2,NaN,No,No,31,38,No
13,STU0014,Male,19,26,63.3,Master,Yes,No,85,64,Yes

In pandas queries can be used to filter data on multiple columns as per requirement

In [29]:
df.query("age > 10 & (attendance_rate > 75.0 & attendance_rate < 80.0)").head()

,student_id,gender,age,study_hours_per_week,attendance_rate,parent_education,internet_access,extracurricular,previous_score,final_score,passed
19,STU0020,Female,18,30,75.9,High School,Yes,Yes,38,70,Yes
29,STU0030,Female,19,29,76.6,High School,Yes,Yes,38,78,Yes
34,STU0035,Male,18,28,77.2,Master,Yes,No,43,62,Yes
40,STU0041,Male,17,26,78.0,PhD,Yes,Yes,50,82,Yes
44,STU0045,Female,17,22,75.5,NaN,No,Yes,44,57,Yes

In [30]:
df["gender_short"] = df["gender"].replace({"Male" : "M", "Female" : "F"})
df[["student_id", "gender", "gender_short"]]

    student_id  gender gender_short
0      STU0001    Male            M
1      STU0002  Female            F
2      STU0003  Female            F
3      STU0004    Male            M
4      STU0005  Female            F
..         ...     ...          ...
495    STU0496  Female            F
496    STU0497  Female            F
497    STU0498  Female            F
498    STU0499    Male            M
499    STU0500    Male            M

[500 rows x 3 columns]

In [31]:
df.query("parent_education == 'High School'").head()

,student_id,gender,age,study_hours_per_week,attendance_rate,parent_education,internet_access,extracurricular,previous_score,final_score,passed,gender_short
2,STU0003,Female,19,10,90.5,High School,Yes,No,73,49,No,F
3,STU0004,Male,16,26,66.8,High School,No,Yes,75,70,Yes,M
4,STU0005,Female,15,25,73.0,High School,No,Yes,67,77,Yes,F
5,STU0006,Female,19,8,85.2,High School,Yes,No,40,37,No,F
8,STU0009,Female,19,9,84.2,High School,Yes,Yes,70,49,No,F

In [32]:
df.query("parent_education == 'High School' & attendance_rate > 85").head()

,student_id,gender,age,study_hours_per_week,attendance_rate,parent_education,internet_access,extracurricular,previous_score,final_score,passed,gender_short
2,STU0003,Female,19,10,90.5,High School,Yes,No,73,49,No,F
5,STU0006,Female,19,8,85.2,High School,Yes,No,40,37,No,F
25,STU0026,Female,18,9,93.7,High School,No,Yes,36,53,Yes,F
32,STU0033,Female,18,12,96.5,High School,Yes,No,42,42,No,F
90,STU0091,Male,16,10,91.3,High School,Yes,Yes,69,60,Yes,M

pandas allows developer to execute function on data frames

In [33]:
def short_parent_education(parent_education):
    if parent_education == "Bachelor":
        return "B"
    elif parent_education == "High School":
        return "HS"
    else:
        return "HQ"

df["parent_education_short"] = df["parent_education"].apply(short_parent_education)
df[["student_id", "parent_education", "parent_education_short"]]

    student_id parent_education parent_education_short
0      STU0001         Bachelor                      B
1      STU0002         Bachelor                      B
2      STU0003      High School                     HS
3      STU0004      High School                     HS
4      STU0005      High School                     HS
..         ...              ...                    ...
495    STU0496           Master                     HQ
496    STU0497              PhD                     HQ
497    STU0498           Master                     HQ
498    STU0499              NaN                     HQ
499    STU0500      High School                     HS

[500 rows x 3 columns]