This Program demonstrates how panda library could be used to read different file formats and process the data

In [11]:
import pandas as pd

try:
    df = pd.read_csv("../dataset/sample.csv")
except Exception as e:
    print(f"Exception: {e}")

df

   sqft  number_of_rooms  price
0   500                2    150
1   750                3    200
2  1000                4    250
3  1250                4    300
4  1500                5    350
5  1750                5    400
6  2000                6    450

Display first three rows only

In [12]:

df.head(3)

   sqft  number_of_rooms  price
0   500                2    150
1   750                3    200
2  1000                4    250

In [13]:
# dispaly only price column from data frame
df["price"]

0    150
1    200
2    250
3    300
4    350
5    400
6    450
Name: price, dtype: int64

In [15]:
df[["price", "number_of_rooms"]]

   price  number_of_rooms
0    150                2
1    200                3
2    250                4
3    300                4
4    350                5
5    400                5
6    450                6

Below is the example how data could be filtered base on specific condition
df[df["price"] > 350]

In [16]:
df[df["price"] > 350]

   sqft  number_of_rooms  price
5  1750                5    400
6  2000                6    450

Below is the example how data could be filtered base on specific condition
df[df["price"] > 350]["sqft"]

In [17]:
df[df["price"] > 350]["sqft"]

5    1750
6    2000
Name: sqft, dtype: int64

In pandas queries can be used to filter data as per requirement

In [25]:
df.query("number_of_rooms > 4").head()

   sqft  number_of_rooms  price
4  1500                5    350
5  1750                5    400
6  2000                6    450

In pandas queries can be used to filter data on multiple columns as per requirement

In [29]:
df.query("number_of_rooms > 4 & (price > 300 & price < 450)").head()

   sqft  number_of_rooms  price
4  1500                5    350
5  1750                5    400